[tool.poetry]
name = "repl_python3_ankio"
version = "0.1.0"
description = ""
authors = ["thainghiep <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
